# Generated by Django 4.2.15 on 2025-03-13 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Website', models.URLField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=1023, null=True)),
                ('AccountManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContactDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ContactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customercontact')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer')),
            ],
        ),
    ]
