# Generated by Django 4.2.15 on 2025-03-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontactdetails',
            name='ContactPerson',
        ),
        migrations.AddField(
            model_name='customercontactdetails',
            name='CustomerContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.customercontact'),
        ),
    ]
