# Generated by Django 4.2.15 on 2025-03-13 11:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_customercontactdetails_contactperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Country',
            field=django_countries.fields.CountryField(max_length=20),
        ),
    ]
