# Generated by Django 4.2.15 on 2025-03-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_customer_country'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['AccountManager'], name='marketing_c_Account_a4078a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['Country'], name='marketing_c_Country_d97ac7_idx'),
        ),
    ]
