# Generated by Django 4.2.15 on 2025-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_customer_marketing_c_account_a4078a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['Customer'], name='marketing_c_Custome_c622c6_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontactdetails',
            index=models.Index(fields=['Customer'], name='marketing_c_Custome_2c27cf_idx'),
        ),
    ]
