# Generated by Django 4.2.15 on 2025-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_customercontact_marketing_c_custome_c622c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerContactDetails',
        ),
    ]
