# Generated by Django 4.2.15 on 2025-04-10 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0006_customercontact_email_customercontact_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Conversation', models.TextField(default='No answer')),
                ('Caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer')),
            ],
        ),
    ]
