# Generated by Django 4.2.15 on 2025-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_calls'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calls',
            index=models.Index(fields=['Caller', 'Customer'], name='marketing_c_Caller__457d24_idx'),
        ),
    ]
