# Generated by Django 4.2.15 on 2025-04-11 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0008_calls_marketing_c_caller__457d24_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calls',
            new_name='Call',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='marketing_c_Caller__ac334a_idx',
            old_name='marketing_c_Caller__457d24_idx',
        ),
    ]
