# Generated by Django 4.2.15 on 2025-02-04 13:48

import apparelManagement.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('IsLocal', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('TradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=15, null=True)),
                ('VATNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentTerms', models.CharField(blank=True, max_length=255, null=True)),
                ('DocumentsURL', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('FullName', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Code', models.CharField(help_text='Slash (/) is not allowed here. Need to add proper carton coding system', max_length=255, primary_key=True, serialize=False, validators=[apparelManagement.models.string_validator])),
                ('Name', models.CharField(max_length=255)),
                ('Group', models.CharField(choices=[('TRIM', 'Trim'), ('WASHING', 'Washing'), ('ELECTRICAL', 'Electrical'), ('FABRIC', 'Fabric'), ('MECHANICAL', 'Mechanical'), ('OTHERS', 'Others'), ('MEDICINE', 'Medicine'), ('STATIONERY', 'Stationery'), ('HOUSEKEEPING', 'Housekeeping'), ('ELECTRONICS', 'Electronics'), ('FXDASSETS', 'Fixed Assets')], max_length=15)),
                ('AuditReq', models.BooleanField(blank=True, default=True)),
                ('Life', models.FloatField(blank=True, default=0, help_text='Days from IH to Expirty')),
                ('InUse', models.BooleanField(blank=True, default=True)),
                ('LeadTime', models.FloatField(blank=True, default=0)),
                ('MinStockLvl', models.FloatField(blank=True, default=0)),
                ('StandardPrice', models.FloatField(blank=True, default=0)),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.currency')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReciept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ReceiptDate', models.DateField(auto_now_add=True)),
                ('Invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('Vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('Bilty', models.CharField(blank=True, max_length=50, null=True)),
                ('BiltyValue', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IssuanceDate', models.DateField(auto_now_add=True)),
                ('ReceivedBy', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.department')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsBank',
            fields=[
                ('Code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Section', models.CharField(choices=[('Small Parts', 'Small Parts'), ('Front', 'Front'), ('Back', 'Back'), ('Assembly 1', 'Assembly 1'), ('Assembly 2', 'Assembly 2'), ('Finishing', 'Finishing')], max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('SkillLevel', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('SMV', models.FloatField(default=0.0)),
                ('MachineReq', models.BooleanField(blank=True, default=True, null=True)),
                ('MachineType', models.CharField(max_length=50)),
                ('Rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('RequestBy', models.CharField(max_length=50)),
                ('Confirmation', models.BooleanField(blank=True, default=False, null=True)),
                ('StoreComments', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.department')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCard',
            fields=[
                ('StyleCode', models.CharField(help_text='Slash (/) is not allowed here.', max_length=255, primary_key=True, serialize=False, validators=[apparelManagement.models.string_validator])),
                ('StyleName', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Boy', 'Boy'), ('Girl', 'Girl'), ('Baby', 'Baby')], max_length=15)),
                ('Notes', models.CharField(max_length=40)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('TradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=15, null=True)),
                ('NTN', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentTerms', models.CharField(blank=True, max_length=255, null=True)),
                ('DocumentsURL', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('StandardUnit', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('OrderNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
                ('Type', models.CharField(choices=[('Export', 'Export'), ('CMT', 'CMT'), ('Local', 'Local'), ('SMS', 'SMS')], max_length=15)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Agent', models.CharField(blank=True, max_length=50, null=True)),
                ('Commission', models.FloatField(blank=True, default=0.0, null=True)),
                ('ExcessCut', models.FloatField(blank=True, default=3.0, null=True)),
                ('Currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.currency')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.customer')),
                ('Merchandiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('StyleCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Factor', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-11, 'Must be greater than 0')])),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StyleVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VariantCode', models.CharField(max_length=50)),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='StyleRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('Stage', models.CharField(blank=True, choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Washing', 'Washing'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing'), ('Embelishment', 'Embelishment')], max_length=50, null=True)),
                ('Cost', models.FloatField(null=True)),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='StyleConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Consumption', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, "Can't be less than 0")])),
                ('Type', models.CharField(blank=True, choices=[('Fab', 'Fabric'), ('BW', 'BW Trim'), ('AW', 'AW Trim')], default='BW', max_length=15, null=True)),
                ('FinalCons', models.FloatField()),
                ('HasVariant', models.BooleanField(blank=True, default=False, null=True)),
                ('SizeDetails', models.CharField(blank=True, max_length=255, null=True)),
                ('InventoryCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
                ('Unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.unit')),
            ],
        ),
        migrations.CreateModel(
            name='StitchOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('Section', models.CharField(blank=True, choices=[('Small Parts', 'Small Parts'), ('Front', 'Front'), ('Back', 'Back'), ('Assembly 1', 'Assembly 1'), ('Assembly 2', 'Assembly 2'), ('Finishing', 'Finishing')], help_text='Will choose OB section if blank.', max_length=255, null=True)),
                ('IsStart', models.BooleanField(blank=True, default=False, null=True)),
                ('IsEnd', models.BooleanField(blank=True, default=False, null=True)),
                ('Operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.operationsbank')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity can't be less than 0")])),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('Requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity an't be less than 0")])),
                ('RequisitionInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.requisitioninventory')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='RecInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity can't be less than 0")])),
                ('Approval', models.BooleanField(blank=True, default=False, null=True)),
                ('QualityComments', models.CharField(blank=True, max_length=255, null=True)),
                ('InventoryCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('ReceiptNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.inventoryreciept')),
            ],
        ),
        migrations.CreateModel(
            name='RecAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity an't be less than 0")])),
                ('RecInvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.recinventory')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
                ('Tax', models.FloatField(blank=True, default=0.0, null=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDemand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DemandDate', models.DateField(auto_now_add=True)),
                ('Demandee', models.CharField(max_length=50)),
                ('Approval', models.BooleanField(blank=True, null=True)),
                ('ApprovedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.department')),
                ('PONumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='POInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity can't be less than 0")])),
                ('Price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Price can't be less than 0")])),
                ('Forex', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-07, "Forex can't be less than 0")])),
                ('Currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.currency')),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('PONumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='POAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.FloatField()),
                ('POInvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.poinventory')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='PDInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity can't be less than 0")])),
                ('Price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Price can't be less than 0")])),
                ('Forex', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-07, "Forex can't be less than 0")])),
                ('Currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.currency')),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('PDNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.purchasedemand')),
            ],
        ),
        migrations.CreateModel(
            name='OrderVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('OrderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='IssueInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity can't be less than 0")])),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('Issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.issuance')),
            ],
        ),
        migrations.CreateModel(
            name='IssueAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, "Quantity an't be less than 0")])),
                ('IssueInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.issueinventory')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='issuance',
            name='InventoryRequisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.requisition'),
        ),
        migrations.CreateModel(
            name='InvRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Variant', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(blank=True, null=True)),
                ('InventoryCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventory')),
                ('OrderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryreciept',
            name='PONumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventoryreciept',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.supplier'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apparelManagement.unit'),
        ),
        migrations.CreateModel(
            name='FinishOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('IsStart', models.BooleanField(blank=True, default=False, null=True)),
                ('IsEnd', models.BooleanField(blank=True, default=False, null=True)),
                ('Operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.operationsbank')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='CoreSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Size', models.CharField(max_length=50)),
                ('Inseam', models.CharField(blank=True, max_length=50, null=True)),
                ('CutDate', models.DateField(auto_now_add=True)),
                ('Cut', models.PositiveIntegerField()),
                ('Bundle', models.PositiveIntegerField()),
                ('Quantity', models.PositiveBigIntegerField()),
                ('OrderNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
    ]
