# Generated by Django 4.2.15 on 2025-02-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCodePart1',
            fields=[
                ('Code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCodePart2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=10)),
                ('Part1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventorycodepart1')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCodePart3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=10)),
                ('Part2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.inventorycodepart2')),
            ],
        ),
    ]
