# Generated by Django 4.2.15 on 2025-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0002_inventorycodepart1_inventorycodepart2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycodepart2',
            name='Code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='inventorycodepart3',
            name='Code',
            field=models.CharField(max_length=5),
        ),
    ]
