# Generated by Django 4.2.15 on 2025-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0003_alter_inventorycodepart2_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycodepart2',
            name='Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='inventorycodepart3',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
