# Generated by Django 4.2.15 on 2025-02-07 13:30

import apparelManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0004_alter_inventorycodepart2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Code',
            field=models.CharField(help_text='Slash (/) is not allowed here. Need to add proper carton coding system', max_length=255, primary_key=True, serialize=False, unique=True, validators=[apparelManagement.models.string_validator]),
        ),
    ]
