# Generated by Django 4.2.15 on 2025-02-08 13:08

import apparelManagement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apparelManagement', '0005_alter_inventory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Code',
            field=models.CharField(help_text='Slash (/) is not allowed here.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[apparelManagement.models.string_validator]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=150)),
                ('Summary', models.CharField(max_length=255)),
                ('Body', models.TextField()),
                ('URL', models.URLField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('IsRead', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['User'], name='apparelMana_User_id_60ec76_idx'), models.Index(fields=['IsRead'], name='apparelMana_IsRead_593ade_idx')],
            },
        ),
    ]
