# Generated by Django 4.2.15 on 2025-02-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0006_alter_inventory_code_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='URL',
            field=models.CharField(max_length=100),
        ),
    ]
