# Generated by Django 4.2.15 on 2025-02-13 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0007_alter_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Rate', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-11, 'Must be greater than 0')])),
            ],
        ),
        migrations.AddIndex(
            model_name='finishob',
            index=models.Index(fields=['Style'], name='apparelMana_Style_i_c70e69_idx'),
        ),
        migrations.AddIndex(
            model_name='stitchob',
            index=models.Index(fields=['Style'], name='apparelMana_Style_i_73a87c_idx'),
        ),
        migrations.AddIndex(
            model_name='styleconsumption',
            index=models.Index(fields=['Style'], name='apparelMana_Style_i_dc5c20_idx'),
        ),
        migrations.AddIndex(
            model_name='styleroute',
            index=models.Index(fields=['Style'], name='apparelMana_Style_i_bc48c8_idx'),
        ),
        migrations.AddIndex(
            model_name='stylevariant',
            index=models.Index(fields=['Style'], name='apparelMana_Style_i_4a12da_idx'),
        ),
        migrations.AddField(
            model_name='forexrate',
            name='Currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.currency'),
        ),
    ]
