# Generated by Django 4.2.15 on 2025-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0008_forexrate_finishob_apparelmana_style_i_c70e69_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stitchob',
            index=models.Index(fields=['Section'], name='apparelMana_Section_d90e14_idx'),
        ),
    ]
