# Generated by Django 4.2.15 on 2025-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0009_stitchob_apparelmana_section_d90e14_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coresheet',
            index=models.Index(fields=['OrderNumber'], name='apparelMana_OrderNu_ad4f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreciept',
            index=models.Index(fields=['PONumber'], name='apparelMana_PONumbe_f0e3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreciept',
            index=models.Index(fields=['ReceiptDate'], name='apparelMana_Receipt_887d60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreciept',
            index=models.Index(fields=['Supplier'], name='apparelMana_Supplie_802f68_idx'),
        ),
        migrations.AddIndex(
            model_name='invrequirement',
            index=models.Index(fields=['OrderNumber'], name='apparelMana_OrderNu_ba2fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordervariant',
            index=models.Index(fields=['OrderNumber'], name='apparelMana_OrderNu_ffd1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='poallocation',
            index=models.Index(fields=['POInvId', 'WorkOrder'], name='apparelMana_POInvId_b09449_idx'),
        ),
        migrations.AddIndex(
            model_name='poinventory',
            index=models.Index(fields=['PONumber', 'Inventory'], name='apparelMana_PONumbe_f10849_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['DeliveryDate'], name='apparelMana_Deliver_ecdd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['Supplier'], name='apparelMana_Supplie_e07c60_idx'),
        ),
        migrations.AddIndex(
            model_name='recinventory',
            index=models.Index(fields=['ReceiptNumber', 'InventoryCode'], name='apparelMana_Receipt_899aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['StyleCode'], name='apparelMana_StyleCo_b5754f_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['Customer'], name='apparelMana_Custome_11e7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['Merchandiser'], name='apparelMana_Merchan_b447cf_idx'),
        ),
    ]
