# Generated by Django 4.2.15 on 2025-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0010_coresheet_apparelmana_ordernu_ad4f7f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['Group'], name='apparelMana_Group_27eac9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['InUse'], name='apparelMana_InUse_ab529b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['AuditReq'], name='apparelMana_AuditRe_6be041_idx'),
        ),
        migrations.AddIndex(
            model_name='pdinventory',
            index=models.Index(fields=['PDNumber', 'Inventory'], name='apparelMana_PDNumbe_2ae469_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedemand',
            index=models.Index(fields=['Department'], name='apparelMana_Departm_41c673_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedemand',
            index=models.Index(fields=['Approval'], name='apparelMana_Approva_e96c85_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedemand',
            index=models.Index(fields=['PONumber'], name='apparelMana_PONumbe_ff9eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='recallocation',
            index=models.Index(fields=['RecInvId', 'WorkOrder'], name='apparelMana_RecInvI_f86f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['Department'], name='apparelMana_Departm_dc06fd_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['DateTime'], name='apparelMana_DateTim_98fee8_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['Confirmation'], name='apparelMana_Confirm_fd940b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionallocation',
            index=models.Index(fields=['RequisitionInventory', 'WorkOrder'], name='apparelMana_Requisi_96af77_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitioninventory',
            index=models.Index(fields=['Requisition', 'Inventory'], name='apparelMana_Requisi_756ec1_idx'),
        ),
    ]
