# Generated by Django 4.2.15 on 2025-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0011_inventory_apparelmana_group_27eac9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleroute',
            name='Stage',
            field=models.CharField(blank=True, choices=[('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Washing', 'Washing'), ('Finishing', 'Finishing'), ('Embroidery', 'Embroidery'), ('Printing', 'Printing'), ('Embelishment', 'Embelishment'), ('Embossing', 'Embossing')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='issuance',
            index=models.Index(fields=['Department'], name='apparelMana_Departm_13d4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='issueallocation',
            index=models.Index(fields=['IssueInventory', 'WorkOrder'], name='apparelMana_IssueIn_f3b54c_idx'),
        ),
        migrations.AddIndex(
            model_name='issueinventory',
            index=models.Index(fields=['Issuance', 'Inventory'], name='apparelMana_Issuanc_6263cf_idx'),
        ),
    ]
