# Generated by Django 4.2.15 on 2025-02-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0012_alter_styleroute_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CheckList', models.CharField(max_length=15)),
                ('Approval', models.BooleanField(blank=True, null=True)),
                ('RecInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.recinventory')),
            ],
            options={
                'indexes': [models.Index(fields=['RecInventory'], name='apparelMana_RecInve_2d56c6_idx'), models.Index(fields=['Approval'], name='apparelMana_Approva_9654cc_idx')],
            },
        ),
    ]
