# Generated by Django 4.2.15 on 2025-02-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0013_inventoryaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryAudit',
        ),
    ]
