# Generated by Django 4.2.15 on 2025-03-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0014_delete_inventoryaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stitchob',
            name='Operation',
        ),
        migrations.RemoveField(
            model_name='stitchob',
            name='Style',
        ),
        migrations.DeleteModel(
            name='FinishOB',
        ),
        migrations.DeleteModel(
            name='OperationsBank',
        ),
        migrations.DeleteModel(
            name='StitchOB',
        ),
    ]
