# Generated by Django 4.2.15 on 2025-05-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0015_remove_stitchob_operation_remove_stitchob_style_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreSheet',
        ),
    ]
