# Generated by Django 5.0.14 on 2025-05-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0016_delete_coresheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Code',
            new_name='id',
        ),
    ]
