# Generated by Django 5.0.14 on 2025-05-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0017_rename_code_inventory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='id',
            new_name='Code',
        ),
    ]
