# Generated by Django 4.2.15 on 2025-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Section', models.CharField(choices=[('Small Parts', 'Small Parts'), ('Front', 'Front'), ('Back', 'Back'), ('Assembly 1', 'Assembly 1'), ('Assembly 2', 'Assembly 2'), ('Finishing', 'Finishing')], max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('SkillLevel', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('SMV', models.FloatField(default=0.0)),
                ('MachineReq', models.BooleanField(blank=True, default=True, null=True)),
                ('MachineType', models.CharField(max_length=50)),
                ('Rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
