# Generated by Django 4.2.15 on 2025-03-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0015_remove_stitchob_operation_remove_stitchob_style_and_more'),
        ('productivityManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('Section', models.CharField(blank=True, choices=[('Small Parts', 'Small Parts'), ('Front', 'Front'), ('Back', 'Back'), ('Assembly 1', 'Assembly 1'), ('Assembly 2', 'Assembly 2'), ('Finishing', 'Finishing')], help_text='Will choose OB section if blank.', max_length=255, null=True)),
                ('IsStart', models.BooleanField(blank=True, default=False, null=True)),
                ('IsEnd', models.BooleanField(blank=True, default=False, null=True)),
                ('Operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productivityManagement.operationsbank')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
            options={
                'indexes': [models.Index(fields=['Style'], name='productivit_Style_i_699ca2_idx'), models.Index(fields=['Section'], name='productivit_Section_961810_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinishOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('IsStart', models.BooleanField(blank=True, default=False, null=True)),
                ('IsEnd', models.BooleanField(blank=True, default=False, null=True)),
                ('Operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productivityManagement.operationsbank')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.stylecard')),
            ],
            options={
                'indexes': [models.Index(fields=['Style'], name='productivit_Style_i_921289_idx')],
            },
        ),
    ]
