# Generated by Django 4.2.15 on 2025-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivityManagement', '0002_stitchob_finishob'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbank',
            name='code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
