# Generated by Django 4.2.15 on 2025-03-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivityManagement', '0003_operationsbank_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationsbank',
            old_name='code',
            new_name='Code',
        ),
    ]
