# Generated by Django 4.2.15 on 2025-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivityManagement', '0004_rename_code_operationsbank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsbank',
            name='Section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operationsbank',
            name='SkillLevel',
            field=models.PositiveIntegerField(),
        ),
    ]
