# Generated by Django 4.2.15 on 2025-03-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivityManagement', '0005_alter_operationsbank_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stitchob',
            name='Section',
            field=models.CharField(blank=True, help_text='Will choose OB section if blank.', max_length=255, null=True),
        ),
    ]
