# Generated by Django 4.2.15 on 2025-02-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apparelManagement', '0014_delete_inventoryaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CheckList', models.CharField(max_length=15)),
                ('Approval', models.BooleanField(blank=True, null=True)),
                ('RecInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparelManagement.recinventory')),
            ],
            options={
                'indexes': [models.Index(fields=['RecInventory'], name='qualityCont_RecInve_6381f1_idx'), models.Index(fields=['Approval'], name='qualityCont_Approva_dbc2db_idx')],
            },
        ),
    ]
