# Generated by Django 4.2.15 on 2025-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='trimaudit',
            name='Comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
