# Generated by Django 4.2.15 on 2025-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Section', models.CharField(max_length=31)),
                ('Category', models.CharField(max_length=31)),
                ('SkillLevel', models.PositiveIntegerField()),
                ('SMV', models.FloatField(blank=True, null=True)),
                ('MachineRequirement', models.BooleanField(default=False)),
                ('MachineType', models.CharField(max_length=31)),
                ('Rate', models.FloatField(blank=True, null=True)),
                ('Code', models.CharField(blank=True, max_length=31, null=True)),
            ],
        ),
    ]
