# Generated by Django 4.2.15 on 2025-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Name',
            field=models.CharField(max_length=511),
        ),
    ]
