# Generated by Django 4.2.15 on 2025-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0002_alter_operation_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['Section'], name='prodManagem_Section_ac47b4_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['MachineType'], name='prodManagem_Machine_50290e_idx'),
        ),
    ]
