# Generated by Django 4.2.15 on 2025-04-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0015_remove_stitchob_operation_remove_stitchob_style_and_more'),
        ('prodManagement', '0003_operation_prodmanagem_section_ac47b4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MachineId', models.CharField(max_length=31)),
                ('PurchaseDate', models.DateField(auto_now_add=True)),
                ('Type', models.CharField(max_length=63)),
                ('FunctionStatus', models.CharField(max_length=15)),
                ('Manufacturer', models.CharField(max_length=15)),
                ('ModelNumber', models.CharField(max_length=15)),
                ('SerialNumber', models.CharField(max_length=15)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.department')),
            ],
            options={
                'indexes': [models.Index(fields=['FunctionStatus', 'Department'], name='prodManagem_Functio_4a314a_idx')],
            },
        ),
    ]
