# Generated by Django 4.2.15 on 2025-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0004_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='ModelNumber',
            field=models.CharField(max_length=25),
        ),
    ]
