# Generated by Django 4.2.15 on 2025-04-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0005_alter_machines_modelnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='ModelNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
