# Generated by Django 4.2.15 on 2025-04-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0015_remove_stitchob_operation_remove_stitchob_style_and_more'),
        ('prodManagement', '0006_alter_machines_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleBulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StyleCard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.stylecard')),
            ],
        ),
        migrations.CreateModel(
            name='StyleBulletinOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.PositiveIntegerField()),
                ('Section', models.CharField(max_length=31)),
                ('IsStart', models.BooleanField(default=False)),
                ('IsEnd', models.BooleanField(default=False)),
                ('Operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prodManagement.operation')),
                ('StyleBulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodManagement.stylebulletin')),
            ],
        ),
    ]
