# Generated by Django 4.2.15 on 2025-04-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0007_stylebulletin_stylebulletinoperation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stylebulletin',
            index=models.Index(fields=['StyleCard'], name='prodManagem_StyleCa_6d484f_idx'),
        ),
        migrations.AddIndex(
            model_name='stylebulletinoperation',
            index=models.Index(fields=['StyleBulletin'], name='prodManagem_StyleBu_380149_idx'),
        ),
        migrations.AddIndex(
            model_name='stylebulletinoperation',
            index=models.Index(fields=['Operation'], name='prodManagem_Operati_eb9131_idx'),
        ),
        migrations.AddIndex(
            model_name='stylebulletinoperation',
            index=models.Index(fields=['Section'], name='prodManagem_Section_a31272_idx'),
        ),
    ]
