# Generated by Django 4.2.15 on 2025-05-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0016_delete_coresheet'),
        ('prodManagement', '0008_stylebulletin_prodmanagem_styleca_6d484f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Shade', models.CharField(max_length=31)),
                ('WarpShrinkage', models.FloatField()),
                ('WeftShrinkage', models.FloatField()),
                ('Inseam', models.CharField(max_length=31)),
                ('NoOfPlies', models.PositiveIntegerField()),
                ('CutNumber', models.PositiveIntegerField()),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Size', models.CharField(max_length=31)),
                ('Bundle', models.PositiveIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('Cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodManagement.cut')),
            ],
        ),
    ]
