# Generated by Django 4.2.15 on 2025-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0009_cut_bundle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['Cut'], name='prodManagem_Cut_id_bc86aa_idx'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['Size'], name='prodManagem_Size_876650_idx'),
        ),
        migrations.AddIndex(
            model_name='cut',
            index=models.Index(fields=['WorkOrder'], name='prodManagem_WorkOrd_00ca66_idx'),
        ),
    ]
