# Generated by Django 4.2.15 on 2025-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0010_bundle_prodmanagem_cut_id_bc86aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='Inseam',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
