# Generated by Django 4.2.15 on 2025-05-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0011_alter_cut_inseam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='Quantity',
        ),
    ]
