# Generated by Django 4.2.15 on 2025-05-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0016_delete_coresheet'),
        ('prodManagement', '0012_remove_bundle_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('WorkerCode', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('WorkerName', models.CharField(max_length=255)),
                ('FatherSpouseName', models.CharField(blank=True, max_length=255, null=True)),
                ('CNIC', models.CharField(blank=True, max_length=255, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('DateOfJoining', models.DateField(auto_now_add=True, null=True)),
                ('Status', models.CharField(max_length=31)),
                ('Gender', models.CharField(max_length=7)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apparelManagement.department')),
            ],
        ),
    ]
