# Generated by Django 4.2.15 on 2025-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0013_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='SubDepartment',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
