# Generated by Django 4.2.15 on 2025-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManagement', '0014_worker_subdepartment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['Department'], name='prodManagem_Departm_944670_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['Status'], name='prodManagem_Status_454da3_idx'),
        ),
    ]
