# Generated by Django 4.2.15 on 2025-05-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodManagement', '0015_worker_prodmanagem_departm_944670_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
