# Generated by Django 5.0.14 on 2025-05-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparelManagement', '0018_rename_id_inventory_code'),
        ('prodManagement', '0016_worker_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machine',
        ),
        migrations.RenameIndex(
            model_name='machine',
            new_name='prodManagem_Functio_813092_idx',
            old_name='prodManagem_Functio_4a314a_idx',
        ),
    ]
